###admin login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email":"admin@mail.com",
    "password":"admin"
}

###read all users & authors(email)
GET http://localhost:4000/admin-api/users


###block user or author
PUT http://localhost:4000/admin-api/user/69b3c80a0aae7f044625f432
Content-Type: application/json

{
  "status": "BLOCKED"
}

###activate user or author
PUT http://localhost:4000/auth/user/USER_ID_HERE/status
Content-Type: application/json

{
  "status": "ACTIVE"
}